### ISSUE TITLE
Para actualizar un estado, mejor usar el valor previo del estado

### ISSUE THREAD

**Issue by itacademyReact** [MireiaBS/Sprint6-React1#1]
No -> ` setIntro(!intro)
`

Si -> `setIntro(prev => !prev)
`

Más info: https://www.youtube.com/watch?v=yvTGXH7uybA

https://github.com/MireiaBS/Sprint6-React1/blob/61b155d68b7cf740ca30ed36e5487c1e5046431f/src/App.js#L15

**Comment by MireiaBS** [comment]
Gracias, ya he hecho los cambios en el sprint 7!
