### ISSUE TITLE
Quizás retocaría esta parte

### ISSUE THREAD

**Issue by itacademyReact** [MireiaBS/Sprint6-React1#2]
En referencia a  ` document.body.style = `background: url('${bg}') no-repeat center center fixed; background-size: cover;`;
`

Está bien, pero lo ideal hubiese sido usar un styled component.

https://github.com/MireiaBS/Sprint6-React1/blob/61b155d68b7cf740ca30ed36e5487c1e5046431f/src/App.js#L23

**Comment by MireiaBS** [comment]
De acuerdo
